### ISSUE TITLE
how can we add new models?

### ISSUE THREAD

**Issue by emrovsky** [MagicalMadoka/funcaptcha-challenger#1]
good stuff!and how can we add new models or increase results?

**Comment by emrovsky** [comment]
![image](https://github.com/MagicalMadoka/funcaptcha-challenger/assets/85563550/cb3ee3b2-a7db-4229-9d8f-832095fdf779)

**Comment by MagicalMadoka** [comment]
Thank you for your interest in the project. To contribute, you can provide labeled data in the format of "filename_expectedIndexPosition.png". This will be used to train and enhance the model's accuracy.

The image size should be (200 * n) by 400 pixels.
