### ISSUE TITLE
sample photo for train model

### ISSUE THREAD

**Issue by M4Nyak** [MagicalMadoka/funcaptcha-challenger#8]
my computer cant find  predict_3d_rollball_animals function when i try import

ImportError: cannot import name 'predict_3d_rollball_animals' from 'funcaptcha_challenger' (C:\Users\mrx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\funcaptcha_challenger\__init__.py)

how can i install predict_3d_rollball_animals function?

**Comment by M4Nyak** [comment]
and not just predict_3d_rollball_animals function :( 
![Ekran Alıntısı](https://github.com/MagicalMadoka/funcaptcha-challenger/assets/119705619/2ed1497e-346f-4206-a6f4-fa76ad9d0d8d)

**Comment by MagicalMadoka** [comment]
Looks like your local version is outdated, please update to the latest version.
```
pip install --upgrade funcaptcha-challenger
```

**Comment by M4Nyak** [comment]
thank you very much it is working now

**Comment by M4Nyak** [comment]
thank you for telling me the solution to my previous problem. now I have a question, I want to improve the model, but I have no idea how to give the model the photo of the correct answer. if you show an example to train the model, I would be very grateful.

**Comment by gokaybiz** [comment]
@M4Nyak You can use pytorch/onnx.
There are two inputs, left and right. One of them stands for reference gesture, other one is grid if I'm not wrong.
both of these inputs are typed as float32[1,3,52,52].

Probably you trying to match gesture + direction and return a value between 0 and 1.
for example:
gesture: ↖
grid: ↘
output: 0.00021
---
gesture: ↖
grid: ↖
output: 0.99998

etc... etc...

**Comment by M4Nyak** [comment]
@gokaybiz  hocam bende Türküm. Benim anlamadığım eğitmek için hangi komutları kullanicağımız ve doğru cevapı nasıl öğreticeğimiz veri biliminde yeniyimde :(

**Comment by MagicalMadoka** [comment]
If this project gets more than 200 stars, I will open source part of the training code. 

Additionally, I recommend opening a new issue to address new problems, rather than modifying the title.
